title: Dennis Ghartey
logo: logo.jpg
description: A data Analyst Proficient in using Excel for  data analysis,SQL for data cleaning, data interrogation and manupulation and Power BI for creating business intelligent reports.   
#show_downloads: true 
#google_analytics: 
theme: jekyll-theme-minimal
